// This code was generated by `SqlHydra.Sqlite` -- v4.1.0.
namespace DbLayer.Database

open SqlHydra
open SqlHydra.Query

module Version =
    let cli = System.Version(4, 1, 0)
    let ns = "DbLayer.Database"
    SqlHydra.Query.VersionCheck.assertIsCompatible cli ns

module main =

    [<CLIMutable>]
    type DanceType = { DanceTypeId: int64; Name: string }

    let DanceType = table<DanceType>

    [<CLIMutable>]
    type DanceTypeTeacher =
        { DanceTypeId: int64; TeacherId: int64 }

    let DanceTypeTeacher = table<DanceTypeTeacher>

    [<CLIMutable>]
    type DefaultAvailability =
        { DefaultAvailabilityId: int64
          TeacherId: int64
          DayOfWeek: int64
          StartTimeUnix: int64
          EndTimeUnix: int64 }

    let DefaultAvailability = table<DefaultAvailability>

    [<CLIMutable>]
    type EventInstance =
        { EventInstanceId: int64
          RecurringEventId: int64
          Canceled: bool
          StartDateTimeUnix: int64
          EndDateTimeUnix: int64 }

    let EventInstance = table<EventInstance>

    [<CLIMutable>]
    type Organization = { OrganizationId: int64; Name: string }

    let Organization = table<Organization>

    [<CLIMutable>]
    type Person =
        { PersonId: int64
          LastName: string
          FirstName: string }

    let Person = table<Person>

    [<CLIMutable>]
    type RecurringEvent =
        { RecurringEventId: int64
          RecurrenceType: int64
          Description: string
          DaysOfWeek: Option<int64>
          StartDateUnix: int64
          EndDateUnix: Option<int64>
          StartTimeUnix: int64
          EndTimeUnix: int64 }

    let RecurringEvent = table<RecurringEvent>

    [<CLIMutable>]
    type RecurringEventSquirrel =
        { RecurringEventId: int64
          SquirrelId: int64 }

    let RecurringEventSquirrel = table<RecurringEventSquirrel>

    [<CLIMutable>]
    type RecurringEventTeacher =
        { RecurringEventId: int64
          TeacherId: int64 }

    let RecurringEventTeacher = table<RecurringEventTeacher>

    [<CLIMutable>]
    type Squirrel =
        { SquirrelId: int64
          SquirrelOwnerId: int64
          Name: string }

    let Squirrel = table<Squirrel>

    [<CLIMutable>]
    type SquirrelOwner =
        { SquirrelOwnerId: int64
          PersonId: Option<int64>
          OrganizationId: Option<int64>
          PhoneNumber: Option<string>
          Email: Option<string> }

    let SquirrelOwner = table<SquirrelOwner>

    [<CLIMutable>]
    type SquirrelTeacher = { SquirrelId: int64; TeacherId: int64 }

    let SquirrelTeacher = table<SquirrelTeacher>

    [<CLIMutable>]
    type Teacher =
        { TeacherId: int64
          FirstName: string
          LastName: string }

    let Teacher = table<Teacher>

    [<CLIMutable>]
    type TrainingRequest =
        { TrainingRequestId: int64
          CaretakerType: int64
          SquirrelName: string
          OrganizationName: Option<string>
          OwnerLastName: Option<string>
          OwnerFirstName: Option<string>
          Email: string
          Phone: Option<string>
          SquirrelId: Option<int64>
          OnboardUsername: Option<string>
          DescriptionOfNeeds: Option<string>
          OnboardingDateTimeUnix: Option<int64> }

    let TrainingRequest = table<TrainingRequest>



type QueryContextFactory =
    { OpenContext: unit -> QueryContext
      OpenContextAsync: unit -> System.Threading.Tasks.Task<QueryContext> }
    // This provider holds no factory-level resources; each connection is owned and disposed by its QueryContext.
    member _.Dispose() = ()

    interface System.IDisposable with
        member this.Dispose() = this.Dispose()

    interface IQueryContextFactory with
        member this.OpenContextAsync() = this.OpenContextAsync()

    static member Create(connectionString: string, ?sqlLogger) =
        let emitter = SqlHydra.Query.SqliteEmitter()

        let createConn () : System.Data.Common.DbConnection =
            new Microsoft.Data.Sqlite.SqliteConnection(connectionString)

        let openContext () =
            let conn = createConn ()
            conn.Open()
            let ctx = new QueryContext(conn, emitter)
            sqlLogger |> Option.iter (fun logger -> ctx.Logger <- logger)
            ctx

        let openContextAsync () =
            task {
                let conn = createConn ()
                do! conn.OpenAsync()
                let ctx = new QueryContext(conn, emitter)
                sqlLogger |> Option.iter (fun logger -> ctx.Logger <- logger)
                return ctx
            }

        { OpenContext = openContext
          OpenContextAsync = openContextAsync }
