// This code was generated by `SqlHydra.Sqlite` -- v3.5.0.
namespace DbLayer.Database

open SqlHydra
open SqlHydra.Query

module Version =
    let cli = System.Version(3, 5, 0)
    let ns = "DbLayer.Database"
    SqlHydra.Query.VersionCheck.assertIsCompatible cli ns

module main =

    [<CLIMutable>]
    type Organization = { OrganizationId: int64; Name: string }

    let Organization = table<Organization>

    [<CLIMutable>]
    type Person =
        { PersonId: int64
          LastName: string
          FirstName: string }

    let Person = table<Person>

    [<CLIMutable>]
    type Squirrel =
        { SquirrelId: int64
          SquirrelOwnerId: int64
          Name: string }

    let Squirrel = table<Squirrel>

    [<CLIMutable>]
    type SquirrelOwner =
        { SquirrelOwnerId: int64
          PersonId: Option<int64>
          OrganizationId: Option<int64>
          PhoneNumber: Option<string>
          Email: Option<string> }

    let SquirrelOwner = table<SquirrelOwner>

    [<CLIMutable>]
    type TrainingRequest =
        { TrainingRequestId: int64
          SquirrelName: string
          CaretakerType: int64
          OrganizationName: Option<string>
          OwnerLastName: Option<string>
          OwnerFirstName: Option<string>
          Email: string
          Phone: Option<string>
          SquirrelId: Option<int64>
          OnboardUsername: Option<string>
          OnboardingDateTime: Option<string>
          DescriptionOfNeeds: Option<string> }

    let TrainingRequest = table<TrainingRequest>


[<System.Obsolete("The HydraBuilders module is no longer needed and will be removed in v4.0.")>]
module HydraBuilders =
    ()


type QueryContextFactory =
    { OpenContext: unit -> QueryContext
      OpenContextAsync: unit -> System.Threading.Tasks.Task<QueryContext> }

    interface IQueryContextFactory with
        member this.OpenContextAsync() = this.OpenContextAsync()

    static member Create(connectionString: string, ?sqlLogger) =
        let compiler = SqlKata.Compilers.SqliteCompiler()

        let createConn () : System.Data.Common.DbConnection =
            new Microsoft.Data.Sqlite.SqliteConnection(connectionString)

        let openContext () =
            let conn = createConn ()
            conn.Open()
            let ctx = new QueryContext(conn, compiler)
            sqlLogger |> Option.iter (fun logger -> ctx.Logger <- logger)
            ctx

        let openContextAsync () =
            task {
                let conn = createConn ()
                do! conn.OpenAsync()
                let ctx = new QueryContext(conn, compiler)
                sqlLogger |> Option.iter (fun logger -> ctx.Logger <- logger)
                return ctx
            }

        { OpenContext = openContext
          OpenContextAsync = openContextAsync }
